name: plugintest
version: 0.1
author: AkaAzee
main: fr.akaazee.plugintest.Main

commands:
  test:
    description: Ceci est une commande test
    permission: test.use
  alert:
    description: Ceci est un boadcast
    permission: bc.use
  spawn:
    description: Ceci est une commande pour se téléporter au spawn
  worldlist:
    description: Donne la liste de tous les mondes sur le serveur